site_name: P2PP Documentation
repo_url: https://github.com/vhspace/p2pp
repo_name: vhspace/p2pp
edit_uri: blob/master/docs/
use_directory_urls: False
docs_dir: '../'
site_dir: '../../site/'

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

plugins:
  - git-committers:
      repository: vhspace/p2pp
      branch: master
  - git-authors

extra_javascript:
  - /_p2pp/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


extra_css:
  - /_p2pp/css/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

theme:
  name: material
  logo: /images/p2pp_logo.png
  favicon: /images/p2pp_logo.png
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: blue
        accent: blue
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: blue
        accent: light blue
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  features:
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - content.action.view

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - User Guide:
      - PrusaSlicer Configuration: prusa_config.md
      - P2PP Configuration: p2pp_config.md
      - P2PP Parameter Overview: p2pp_param_overview.md
      - Blobster Setup: blobster.md
      - First Print Calibration: first_print_calibration.md
  - Process Flow: process_flow.md
  - Purge Length Calculation: purge_length_calc.md
  - Reference Configurations: ref_configs.md
  - Troubleshooting: troubleshooting.md
  - Developer Guide:
      - Code Overview: code_overview.md
      - Building P2PP: building_p2pp.md
      - Contributing: contributing.md
  - FAQ: faq.md